Intro to HTML
teodoratsaneva/Internship-FrontEnd pull request #1
Opened 2023-12-01 09:43 UTC by teodoratsaneva

2023-12-13 09:01 UTC, todorzag commented on Site/Style.css
> +.paragraf {
Formatting

2023-12-13 09:01 UTC, todorzag commented on Site/Style.css
> +  margin-top: 40px;
Try using shorthand syntax

2023-12-19 08:30 UTC, Tanya-Zheleva requested changes

2023-12-19 09:02 UTC, todorzag commented on Site/Style.css
> +.bottom-container input[type=text] {
Try playing with the width property to make it properly resizable when in mobile phone view, look into "vw" unit

2023-12-19 09:05 UTC, Tanya-Zheleva commented on Site/Style.css
> +}
Consider using flex for for the alignment of the components in the header instead of margins / paddings

2024-01-05 15:02 UTC, todorzag commented on Site/Style.css
> +  width: 90vw;
Might not be needed as it currently hinders it from being centered

2024-01-11 16:28 UTC, Tanya-Zheleva approved these changes

2024-03-03 17:50 UTC, merged