Intro to JS
teodoratsaneva/Internship-FrontEnd pull request #2
Opened 2023-12-21 12:04 UTC by teodoratsaneva

2024-01-03 09:00 UTC, Tanya-Zheleva requested changes

2024-01-03 09:00 UTC, Tanya-Zheleva commented on ConditionalStatements.js
> +    }
Can the code from task 3 be reused here ?

2024-01-03 09:00 UTC, Tanya-Zheleva commented on ConditionalStatements.js
> +    }
Same for Task 7

2024-01-05 15:41 UTC, todorzag commented on Arrays.js
> +        if (array[i] === array[i - 1]) {
Doesn't array[i - 1] return undefined when i is 0?

2024-01-05 15:41 UTC, todorzag commented on Arrays.js
> +        if (array[i] > array[i - 1]) {
Same as above comment for undefined

2024-01-05 16:00 UTC, Tanya-Zheleva commented on Strings.js
> +    return string.split(word).length - 1;
This should be case insensitive.

2024-01-08 16:45 UTC, Tanya-Zheleva requested changes

2024-01-08 16:45 UTC, Tanya-Zheleva commented on LinkedList.js
> +            next: this.head
Is this correct? Won't all new nodes point to the head in this case? Don't they need to be node1 -> node2 -> node3 etc

2024-01-08 16:45 UTC, Tanya-Zheleva commented on LinkedList.js
> +            next: this.head
Also will this link correctly the new nodes with the old ones? Shouldn't the last of of the new nodes point to the old head?

2024-01-10 10:39 UTC, teodoratsaneva commented on LinkedList.js
> +            next: this.head
In the task the function prepend has to add the provided elements to the beginning of the list. With map function I used to create an array of new nodes each having a data field and next field pointing to the current head of the list and it creates a chain of nodes, where each new node points to the previous head

2024-01-11 16:29 UTC, Tanya-Zheleva requested changes

2024-01-11 16:29 UTC, Tanya-Zheleva commented on LinkedList.js
> +                    index--;
Don't change index. I know it's a copy, but it's still not considered a good practice

2024-01-11 16:29 UTC, Tanya-Zheleva commented on LinkedList.js
> +                this.head = node;
If you pass index 0 for prepending, and we have [4, 5, 6].prepend(1, 2, 3), won't this result in [3, 2, 1, 4, 5, 6] instead of [1, 2, 3, 4, 5, 6] ?

2024-01-11 16:29 UTC, Tanya-Zheleva commented on LinkedList.js
> +    at(index) {
Isn't this zero based? Even if not - you can return the head above the while

2024-01-11 16:29 UTC, Tanya-Zheleva commented on LinkedList.js
> +                while (current && index > 1) {
Why not index > 0 ?
Also as a suggestion, you could keep a reference to the tail as well. It will be easier to append items at the end

2024-01-11 16:29 UTC, Tanya-Zheleva commented on LinkedList.js
> +    // }
Remove this if it's not needed

2024-03-03 17:49 UTC, merged