creating  components and navigation functionality
teodoratsaneva/Internship-FrontEnd pull request #6
Opened 2024-01-22 15:28 UTC by teodoratsaneva

2024-01-24 09:52 UTC, Tanya-Zheleva requested changes

2024-01-24 09:52 UTC, Tanya-Zheleva commented on my-project/src/cook-page.tsx
> +    )
Formatting

2024-01-24 09:52 UTC, Tanya-Zheleva commented on my-project/src/cook-page.tsx
> +    )
All files formatting should be 1 tab (4 spaces)

2024-01-24 09:52 UTC, Tanya-Zheleva commented on my-project/src/index.less
> +}
These can be combined

2024-01-24 09:52 UTC, Tanya-Zheleva commented on my-project/src/index.less
> +}
Formatting, remove unneeded new line

2024-01-24 09:52 UTC, Tanya-Zheleva commented on my-project/src/home-page.tsx
> +        </Link>
Instead of using Link with input inside, create a Button that uses the MUI button components and reuse it. You can pass what is needed from props

2024-01-24 09:52 UTC, Tanya-Zheleva commented on my-project/src/header-page-component.tsx
> +        <div className="header">
Use header tag

2024-01-24 09:52 UTC, Tanya-Zheleva commented on my-project/src/recipes-container/data-recipes.tsx
> +        { id: "15", text: "11b sirene feta"},
Keep the nested ingredients list in the same format with id, title and ingredientList (you can change it to just ingredients)

2024-01-24 09:52 UTC, Tanya-Zheleva commented on my-project/src/recipes-container/recipe-item.tsx
> +}
Move the interfaces into a separate folder in src/interfaces

2024-01-24 09:52 UTC, Tanya-Zheleva commented on my-project/src/recipes-container/recipe-item.tsx
> +                subIcon={<Brightness2Icon className="Brightness2Icon" />}
Try to create a separate Icon component and use it. It should accept a type prop, and internally decide which exact icon to render.

2024-01-24 09:52 UTC, Tanya-Zheleva commented on my-project/src/recipes-container/recipe-item.tsx
> +                subIcon={<Brightness2Icon className="Brightness2Icon" />}
Try to create a separate Icon component and use it. It should accept a type prop, and internally decide which exact icon to render

2024-01-24 09:52 UTC, Tanya-Zheleva commented on my-project/src/index.less
> +input[type=cook-button]{
Use class name

2024-01-24 09:52 UTC, Tanya-Zheleva commented on my-project/src/cookbook-page.tsx
> +        </h1>
Extract a Heading component and use Typography from MUI there. This can be done for all h1 components. This if it be incorporated for h2 as well

2024-01-30 14:52 UTC, Tanya-Zheleva requested changes

2024-02-01 08:47 UTC, teodoratsaneva commented on my-project/src/recipes-container/recipe-form.tsx
> +					to="/cook"
In spec this is button that will redirect to a new page - the cooking page

2024-02-15 09:26 UTC, Tanya-Zheleva requested changes

2024-02-15 09:26 UTC, Tanya-Zheleva commented on my-project/src/cook-page-components/cook-arena.tsx
> +	const ingredientsCount = useRef(allIngredientsCount);
Can you pass the ingredients count to the cooking arena as a prop? The reason for this is that the arena doesn't need to know 'how' to count them, it just needs a number

2024-02-15 09:26 UTC, Tanya-Zheleva commented on my-project/src/cook-page-components/cook-arena.tsx
> +				p.background(255, 255, 255, 0);
Reuse the consts from above. Extract the other numbers as well

2024-02-15 09:26 UTC, Tanya-Zheleva commented on my-project/src/cook-page-components/ingredient-seg.tsx
> +        ingredient: Ingredient,
Try to add default values for width and height. This way you can skip passing them to the constructor unless you want a bigger image. Also why does the segment need to know about the size of the canvas? Try to avoid passing and canvasHeight.

2024-02-15 09:26 UTC, Tanya-Zheleva commented on my-project/src/common-components/footer.tsx
> +  );
Try to pass a 'configuration' for the buttons that need to be rendered. This means passing an array with information which you then map to buttons here. This would be useful specially if you might need to a add a third button here since adding onClickButton3 will make the component hard to maintain

2024-02-15 10:00 UTC, Tanya-Zheleva commented on my-project/src/modal-create-recipe/modal-component.tsx
> +				}
Can you combine these two?

2024-02-15 10:04 UTC, Tanya-Zheleva commented on my-project/src/pages/cook-page.tsx
> +	const checkDiscoMode = (discoColor, p: p5) => {
Update the name, it should be triggerDiscoMode

2024-02-15 10:07 UTC, Tanya-Zheleva commented on my-project/src/pages/cook-page.tsx
> +				/>
Try to create higher order component called withDiscoModeArena, which wraps the CookArena component. The idea is that all the disco logic is separated there (and not in the cook page) and it should pass the required props to the cooking arena

2024-02-15 10:08 UTC, Tanya-Zheleva commented on my-project/src/pages/cook-page.tsx
> +	};
This should be onLifeLoss, and it should call just setHearts(hearts - 1)

2024-02-15 10:08 UTC, Tanya-Zheleva commented on my-project/src/pages/cook-page.tsx
> +				"#" + Math.floor(Math.random() * 16777215).toString(16);
Use consts here

2024-02-15 10:11 UTC, Tanya-Zheleva commented on my-project/src/cook-page-components/cook-arena.tsx
> +					if (countIngredients < ingredients.length + 1) {
Why not countIngredients <= ingredients.length

2024-02-15 10:15 UTC, Tanya-Zheleva commented on my-project/src/cook-page-components/cook-arena.tsx
> +						);
Shouldn't this be an integer all the time? If it's not, you should be parsing it where the ingredient is being added the first time

2024-02-15 10:20 UTC, Tanya-Zheleva commented on my-project/src/cook-page-components/cook-arena.tsx
> +							discoColor.current = true;
Format the if / else if statements properly
if (!(ingredient.isVisible && ingredient.collidesWith(pot)))

Also can you try to switch the statements, so you don't do negations as they are harder to read

2024-02-15 10:21 UTC, Tanya-Zheleva commented on my-project/src/cook-page-components/cook-arena.tsx
> +								ingredientsCount.current - 1;
Use -=

2024-02-15 10:25 UTC, Tanya-Zheleva commented on my-project/src/cook-page-components/ingredient-seg.tsx
> +        p: p5,
Can you extract a wrapper Interface + class for the drawing library. You can name it Drawer or something like that and it should expose the methods that you need. For example for drawing, for resetting, for updating. Inside the class you should call the p5 methods. This is useful because it will allow an easy change of the drawing library if needed. The components won't know what mechanism for drawing is used, they will be using just an interface. For more info you can check the bridge and adapter design patterns

2024-02-15 10:26 UTC, Tanya-Zheleva commented on my-project/src/cook-page-components/pot-seg.tsx
> +        this.p.image(this.image, this.x, this.y, this.width, 200);
Extract consts

2024-02-27 16:20 UTC, Tanya-Zheleva requested changes

2024-02-27 16:20 UTC, Tanya-Zheleva commented on my-project/src/modal-create-recipe/form.tsx
> +					onAddIngredient={() => handleAddIngredient()}
Just 					onAddIngredient={handleAddIngredient}

2024-02-27 16:20 UTC, Tanya-Zheleva commented on my-project/src/modal-create-recipe/ingredient-recipe-component.tsx
> +		<div style={{ marginLeft: parentId ? "20px" : "0" }}>
Don't use inline css, pass a class name

2024-02-27 16:20 UTC, Tanya-Zheleva commented on my-project/src/modal-create-recipe/ingredient-recipe-component.tsx
> +					<AddIngredient onAddIngredient={() => onAddIngredient()} />
onAddIngredient={onAddIngredient}

2024-02-27 16:20 UTC, Tanya-Zheleva commented on my-project/src/__test__/home-page.test.tsx
> +    expect(modal).toBeInTheDocument();
You can also add a check if the createButton has been called

2024-02-27 19:19 UTC, teodoratsaneva commented on my-project/src/cook-page-components/cook-arena.tsx
> +	ingredientsCount
I can't use the length property of the array, because every ingredient has specific amount and that's why I count all if the ingredients in CookPage in property allIngredientsCount. Then, when catching the ingredient, I decrease the corresponding amount by one

2024-02-27 19:40 UTC, teodoratsaneva commented on my-project/src/modal-create-recipe/form.tsx
> +					onAddIngredient={() => handleAddIngredient()}
I have to use arrow functions, when passing functions as props to components, to ensure the context of this if it's important, or to pass additional arguments

2024-02-27 19:40 UTC, teodoratsaneva commented on my-project/src/modal-create-recipe/ingredient-recipe-component.tsx
> +					<AddIngredient onAddIngredient={() => onAddIngredient()} />
Same here, I have to use arrow functions, when passing functions as props to components, to ensure the context of this if it's important, or to pass additional arguments

2024-02-29 10:35 UTC, Tanya-Zheleva requested changes

2024-02-29 10:35 UTC, Tanya-Zheleva commented on my-project/src/common-components/footer.tsx
> +          component={button.linkTo ? Link : 'button'}
Why not just pass the button component and variant directly as a prop

2024-02-29 10:35 UTC, Tanya-Zheleva commented on my-project/src/cook-page-components/drawer.tsx
> +    }
Lets discuss passing and additional param to the constructor here.

2024-02-29 10:35 UTC, Tanya-Zheleva commented on my-project/src/cook-page-components/drawer.tsx
> +        invalidIngredient: Ingredient
Do you need to pass ingredientIconMap? This is more like a utility and can be called directly here. Also can you create the segments here instead of passing them. Same question for invalidIngredient. Will there be 1 invalid igredient or multiple?

2024-02-29 10:35 UTC, Tanya-Zheleva commented on my-project/src/cook-page-components/drawer.tsx
> +                    const ingredientAmount = ingredients[countIngredients].amount;
Destruct title from ingredients[countIngredients]. Try not to use abbreviations

2024-02-29 10:35 UTC, Tanya-Zheleva commented on my-project/src/cook-page-components/ingredient-seg.tsx
> +    height: number = 100;
You can move width, height above as consts

2024-02-29 10:35 UTC, Tanya-Zheleva commented on my-project/src/cook-page-components/ingredient-seg.tsx
> +        drawer: P5Drawer,
Use drawer interface

2024-02-29 10:35 UTC, Tanya-Zheleva commented on my-project/src/cook-page-components/pot-seg.tsx
> +    height: number = 200;
Move above as consts

2024-02-29 10:35 UTC, Tanya-Zheleva commented on my-project/src/cook-page-components/pot-seg.tsx
> +    constructor(x: number, y: number, image: any, drawer: P5Drawer) {
Use interface instead of class name

2024-02-29 10:35 UTC, Tanya-Zheleva commented on my-project/src/cook-page-components/pot-seg.tsx
> +        this.display();
What does xin stand for? Use a better name

2024-02-29 10:35 UTC, Tanya-Zheleva commented on my-project/src/cook-page-components/spawn-invalid-ingredient.tsx
> +};
Isn't this repeated in another file?

2024-02-29 11:31 UTC, Tanya-Zheleva requested changes

2024-02-29 11:31 UTC, Tanya-Zheleva commented on my-project/src/cook-page-components/with-disco-mode-arena.tsx
> +    const triggerDiscoMode = (p5Drawer: P5Drawer, discoColor: boolean) => {
discoColor doen't sound like a boolean variable. Update the name

2024-02-29 11:31 UTC, Tanya-Zheleva commented on my-project/src/modal-create-recipe/save-modal-component.tsx
> +		});
Create a single point of return

2024-02-29 11:31 UTC, Tanya-Zheleva commented on my-project/src/modal-create-recipe/save-modal-component.tsx
> +		setRecipe({ ...recipe, ingredients: updatedIngredients });
Single point of return

2024-02-29 11:31 UTC, Tanya-Zheleva commented on my-project/src/pages/cook-page.tsx
> +	}
You can move this above as it is an utility. Update the name to getRecipeSaveDate

2024-02-29 11:31 UTC, Tanya-Zheleva commented on my-project/src/pages/cook-page.tsx
> +	}, []);
Can this be a single method which receives a parameter open, and calls setOpen with it

2024-02-29 11:31 UTC, Tanya-Zheleva commented on my-project/src/pages/cook-page.tsx
> +	const onCatch = (id: string, ingredientsCount: number) => {
Isn't ingredientsCount more like caughtIngredientsCount

2024-02-29 11:31 UTC, Tanya-Zheleva commented on my-project/src/pages/cook-page.tsx
> +		});
Why do you need this setRecipe? I don't see where you are calling it

2024-02-29 11:31 UTC, Tanya-Zheleva commented on my-project/src/pages/cook-page.tsx
> +				/>
Won't this show the complete modal every time?

2024-02-29 11:31 UTC, Tanya-Zheleva commented on my-project/src/recipes-container/recipe-form.tsx
> +          }
Extract before return

2024-02-29 11:31 UTC, Tanya-Zheleva commented on my-project/src/recipes-container/recipe-item.tsx
> +            )}
Format this

2024-02-29 11:31 UTC, Tanya-Zheleva commented on my-project/src/recipes-container/recipe-item.tsx
> +            )}
Same for ingredient.amount !== 0 && (next statement)

2024-03-03 17:48 UTC, merged